openapi: 3.0.3
info:
  title: HRIS V2
  version: 1.0.0
servers:
  - url: 'https://hris_backend.ulbi.ac.id/'
paths:
  /api/v2/wage/temp:
    post:
      tags:
        - Slip
      summary: Slip Gaji Temporary
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                phonenum: 'phonenum'
                tanggal_tahun: 'YYYYMM'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/honour/temp:
    post:
      tags:
        - Slip
      summary: Slip Honour Temporary
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                phonenum: 'phonenum'
                tanggal_tahun: 'YYYYMM'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/rkp/excel:
    post:
      tags:
        - Recap
      summary: Rekap
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                phonenum: 'phonenum'
                tanggal_tahun: 'YYYYMM'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
